import turtle
def espada(x: float, y: float, s: float, cor: str):
    Aa = ((x)*s,(y)*s)
    Ab = ((x)*s,(y+15)*s)
    Ac = ((x+10)*s,(y+15)*s)
    Ad = ((x+10)*s,(y+20)*s)
    Ae = ((x+15)*s,(y+20)*s)
    Af = ((x+15)*s,(y+25)*s)
    Ag = ((x+20)*s,(y+25)*s)
    Ah = ((x+20)*s,(y+30)*s)
    Ai = ((x+15)*s,(y+30)*s)
    Aj = ((x+15)*s,(y+40)*s)
    Ak = ((x+10)*s,(y+40)*s)
    Al = ((x+10)*s,(y+50)*s)
    Am = ((x+20)*s,(y+50)*s)
    An = ((x+20)*s,(y+45)*s)
    Ao = ((x+25)*s,(y+45)*s)
    Ap = ((x+25)*s,(y+40)*s)
    Aq = ((x+30)*s,(y+40)*s)
    Ar = ((x+30)*s,(y+45)*s)
    As = ((x+35)*s,(y+45)*s)
    At = ((x+35)*s,(y+50)*s)
    Au = ((x+40)*s,(y+50)*s)
    Av = ((x+40)*s,(y+55)*s)
    Aw = ((x+45)*s,(y+55)*s)
    Ax = ((x+45)*s,(y+60)*s)
    Ay = ((x+50)*s,(y+60)*s)
    Az = ((x+50)*s,(y+65)*s)
    Ba = ((x+55)*s,(y+65)*s)
    Bb = ((x+55)*s,(y+70)*s)
    Bc = ((x+60)*s,(y+70)*s)
    Bd = ((x+60)*s,(y+75)*s)
    Be = ((x+65)*s,(y+75)*s)
    Bf = ((x+65)*s,(y+80)*s)
    Bg = ((x+80)*s,(y+80)*s)
    Bh = ((x+80)*s,(y+65)*s)
    Bi = ((x+75)*s,(y+65)*s)
    Bj = ((x+75)*s,(y+60)*s)
    Bk = ((x+70)*s,(y+60)*s)
    Bl = ((x+70)*s,(y+55)*s)
    Bm = ((x+65)*s,(y+55)*s)
    Bn = ((x+65)*s,(y+50)*s)
    Bo = ((x+60)*s,(y+50)*s)
    Bp = ((x+60)*s,(y+45)*s)
    Bq = ((x+55)*s,(y+45)*s)
    Br = ((x+55)*s,(y+40)*s)
    Bs = ((x+50)*s,(y+40)*s)
    Bt = ((x+50)*s,(y+35)*s)
    Bu = ((x+45)*s,(y+35)*s)
    Bv = ((x+45)*s,(y+30)*s)
    Bw = ((x+40)*s,(y+30)*s)
    Bx = ((x+40)*s,(y+25)*s)
    By = ((x+45)*s,(y+25)*s)
    Bz = ((x+45)*s,(y+20)*s)
    Ca = ((x+50)*s,(y+20)*s)
    Cb = ((x+50)*s,(y+10)*s)
    Cc = ((x+40)*s,(y+10)*s)
    Cd = ((x+40)*s,(y+15)*s)
    Ce = ((x+30)*s,(y+15)*s)
    Cf = ((x+30)*s,(y+20)*s)
    Cg = ((x+25)*s,(y+20)*s)
    Ch = ((x+25)*s,(y+15)*s)
    Ci = ((x+20)*s,(y+15)*s)
    Cj = ((x+20)*s,(y+10)*s)
    Ck = ((x+15)*s,(y+10)*s)
    Cl = ((x+15)*s,(x)*s)
    Cm = ((x+10)*s,(y+10)*s)
    Cn = ((x+25)*s,(y+25)*s)
    Co = ((x+35)*s,(y+25)*s)
    Cp = ((x+35)*s,(y+30)*s)
    Cq = ((x+30)*s,(y+30)*s)
    Cr = ((x+30)*s,(y+35)*s)
    Cs = ((x+25)*s,(y+35)*s)

    turtle.color(cor)
    turtle.hideturtle()
    turtle.up()
    turtle.goto(Aa)
    turtle.down()
    turtle.goto(Ab)
    turtle.goto(Ac)
    turtle.goto(Ad)
    turtle.goto(Ae)
    turtle.goto(Af)
    turtle.goto(Ag)
    turtle.goto(Ah)
    turtle.goto(Ai)
    turtle.goto(Aj)
    turtle.goto(Ak)
    turtle.goto(Al)
    turtle.goto(Am)
    turtle.goto(An)
    turtle.goto(Ao)
    turtle.goto(Ap)
    turtle.goto(Aq)
    turtle.goto(Ar)
    turtle.goto(As)
    turtle.goto(At)
    turtle.goto(Au)
    turtle.goto(Av)
    turtle.goto(Aw)
    turtle.goto(Ax)
    turtle.goto(Ay)
    turtle.goto(Az)
    turtle.goto(Ba)
    turtle.goto(Bb)
    turtle.goto(Bc)
    turtle.goto(Bd)
    turtle.goto(Be)
    turtle.goto(Bf)
    turtle.goto(Bg)
    turtle.goto(Bh)
    turtle.goto(Bi)
    turtle.goto(Bj)
    turtle.goto(Bk)
    turtle.goto(Bl)
    turtle.goto(Bm)
    turtle.goto(Bn)
    turtle.goto(Bo)
    turtle.goto(Bp)
    turtle.goto(Bq)
    turtle.goto(Br)
    turtle.goto(Bs)
    turtle.goto(Bt)
    turtle.goto(Bu)
    turtle.goto(Bv)
    turtle.goto(Bw)
    turtle.goto(Bx)
    turtle.goto(By)
    turtle.goto(Bz)
    turtle.goto(Ca)
    turtle.goto(Cb)
    turtle.goto(Cc)
    turtle.goto(Cd)
    turtle.goto(Ce)
    turtle.goto(Cf)
    turtle.goto(Cg)
    turtle.goto(Ch)
    turtle.goto(Ci)
    turtle.goto(Cj)
    turtle.goto(Ck)
    turtle.goto(Cl)
    turtle.goto(Aa)
    turtle.up()
    turtle.goto(Ck)
    turtle.down()
    turtle.goto(Cm)
    turtle.goto(Ac)
    turtle.up()
    turtle.goto(Cg)
    turtle.down()
    turtle.goto(Cn)
    turtle.goto(Ag)
    turtle.up()
    turtle.goto(Bx)
    turtle.down()
    turtle.goto(Co)
    turtle.goto(Cp)
    turtle.goto(Cq)
    turtle.goto(Cr)
    turtle.goto(Cs)
    turtle.goto(Ap)

espada(0,0,1,"black")
turtle.done()